# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .category_channel import *
from .channel_permission import *
from .get_color import *
from .get_local_image import *
from .get_member import *
from .get_permission import *
from .get_role import *
from .get_server import *
from .get_system_channel import *
from .invite import *
from .managed_server import *
from .member_roles import *
from .message import *
from .news_channel import *
from .provider import *
from .role import *
from .role_everyone import *
from .server import *
from .system_channel import *
from .text_channel import *
from .voice_channel import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_discord.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_discord.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "discord",
  "mod": "index/categoryChannel",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/categoryChannel:CategoryChannel": "CategoryChannel"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/channelPermission",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/channelPermission:ChannelPermission": "ChannelPermission"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/invite",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/invite:Invite": "Invite"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/managedServer",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/managedServer:ManagedServer": "ManagedServer"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/memberRoles",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/memberRoles:MemberRoles": "MemberRoles"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/message",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/message:Message": "Message"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/newsChannel",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/newsChannel:NewsChannel": "NewsChannel"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/role",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/role:Role": "Role"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/roleEveryone",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/roleEveryone:RoleEveryone": "RoleEveryone"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/server",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/server:Server": "Server"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/systemChannel",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/systemChannel:SystemChannel": "SystemChannel"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/textChannel",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/textChannel:TextChannel": "TextChannel"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/voiceChannel",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/voiceChannel:VoiceChannel": "VoiceChannel"
  }
 },
 {
  "pkg": "discord",
  "mod": "index/webhook",
  "fqn": "pulumi_discord",
  "classes": {
   "discord:index/webhook:Webhook": "Webhook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "discord",
  "token": "pulumi:providers:discord",
  "fqn": "pulumi_discord",
  "class": "Provider"
 }
]
"""
)
