name: Pulumi Preview

on:
  pull_request:
    branches:
      - main

jobs:
  pulumi-preview:
    name: Pulumi Preview
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Download Pulumi state
        uses: actions/download-artifact@v4
        with:
          name: pulumi-state
          path: .pulumi/stacks

      - name: Set up Pulumi for local state
        run: pulumi login --local

      - name: Run Pulumi Preview
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: slatedb-pulumi/prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
