name: Pulumi Up

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  pulumi-preview:
    name: Pulumi Up
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: slatedb/slatedb-pulumi/prod
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
